# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
# gem "jekyll"
gem 'github-pages', '~> 228', group: :jekyll_plugins
gem 'wdm', '>= 0.1.0', :install_if => Gem.win_platform?

platforms :mingw, :x64_mingw, :mswin, :jruby do
    gem "tzinfo", ">= 1", "< 3"
    gem "tzinfo-data"
  end